apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-oauth-credentials
  namespace: dex
stringData:
  client-id: Iv1.a9f0b85fcb41a35a
  client-secret: b28123622d4d0bb01adeeb9c05319e3645a91e58

