apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: route53-dynamic-dns-aws-secret
    namespace: route53-dynamic-dns
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B7NiDduU9VFB0xHnSySphOH5/VI=,iv:TB4poINORtxvReBJPskXkLsm/GhChwKh9qzWdrG0U+s=,tag:yf9H+3An6rZnAv5eSyupGw==,type:str]
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:kr45A8jdt7Ks/e6iilGZqqsCNeizh10/Hk9qo65o80GDALYRb9AMhA==,iv:ueZbblfUlqKS5M30IwyV0v+31x2v9vVtkZBIk9YGbiY=,tag:kZjtcygZSlV6SXAfX2mIaA==,type:str]
sops:
    age:
        - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Umtud2JZZTBxOWtLelhR
            Mk5YTGZQN0pRU1JYckRsaGdZSlE1MVd5Y2hFCkhtc1lIditBbUVrTmlST1ROM3F3
            ZVN6eThHdHp6TDdJWm5iSytlVTEyYWsKLS0tIDZpM2tnUHlIbmtmdFlqSG0xMlFQ
            ZVptdWZiQVQvWUFpR24zUnNLbGhGcnMKk8YTFiRxjML91ho+kKmcheW5xm6k3e+e
            IGw/CBBww5G7KV0qZ9w89fHoNyuQXT2xgJ/es8zMPSXnmgtlfJA6vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T09:43:02Z"
    mac: ENC[AES256_GCM,data:6hAN82oRRlsk0Fp1ET8nuXKNumkCAIupcVgErQZquFVfJTjpfu9CJzzwleX+JT+XNJxATo5GX9/aZEjsFU+PYEMsP8kgpis0K9X8Tuf78pt3BZ4h2POz4mrim87NVlETFoR6tin9m5xxRBuivGGxt8SLTwSRT2ajvGLz9FrK8RE=,iv:Bd+BJAOe0x8cP9844GsgoklZivDG5pDHi1AlfSXUSgA=,tag:6jrtbbHhsEVntDAYxy1ZBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
