---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: metallb
spec:
  targetNamespace: metallb-system
  createNamespace: true
  version: 0.14.9
  chart: metallb
  repo: https://metallb.github.io/metallb
